apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: store-front
  template:
    metadata:
      labels:
        app: store-front
    spec:
      containers:
        - name: store-front
          image: viphan123/store-front:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: store-front-service
spec:
  selector:
    app: store-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
