apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      containers:
        - name: store-admin
          image: viphan123/store-admin:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: store-admin-service
spec:
  selector:
    app: store-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
