apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: virtual-worker
  template:
    metadata:
      labels:
        app: virtual-worker
    spec:
      containers:
        - name: virtual-worker
          image: viphan123/virtual-worker:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: virtual-worker-service
spec:
  selector:
    app: virtual-worker
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

